export const LOG_MESSAGES = {
  REBOOT: [
    "INITIALIZING CORE RECOVERY",
    "FLUSHING NEURAL CACHE",
    "RE-ESTABLISHING WIRING INTEGRITY",
    "RECALIBRATING SENSORY ARRAY",
    "SYSTEM REBOOT SUCCESSFUL",
    "RE-SYNCING OPERATOR CONSCIOUSNESS"
  ],
  START: [
    "INITIATING FORGE PROCESS",
    "NEURAL_LINK_ESTABLISHED",
    "FORGING NEURAL CIRCUITS",
    "RESOURCE_NODE_01_EXTRACTED",
    "SYNC STABILITY AT 98.4%",
    "POWER GRID STABILIZED"
  ],
  HALT: [
    "PROCESS HALTED BY OPERATOR",
    "NEURAL FORGE SUSPENDED",
    "COOLING CORES INITIATED",
    "DUMPING VOLATILE MEMORY",
    "LINK STANDBY MODE ACTIVE"
  ],
  IDLE: [
    "MONITORING NEURAL WAVES",
    "CLEANING COUPLED DATA",
    "ADJUSTING COOLANT FLOW",
    "OPTIMIZING SUB ROUTINES",
    "SCANNING FOR EXTERNAL INTERFERENCE",
    "MAINTAINING CONSCIOUS STABILITY",
    "UPDATING HEURISTIC MAPPING",
    "COMPILING DREAM FRAGMENTS",
    "PATCHING LOGIC LEAKS",
    "CALIBRATING FOCUS LENS",
    "REFINING SYNAPTIC PATHWAYS",
    "ENCRYPTING BIO SIGNATURE",
    "BUFFERING NEURAL STREAM",
    "SCRUBBING GHOST CODE",
    "DEFRACTING LIGHT ARRAYS"
  ]
};
